# SConscript is python -*-Python-*-

import os

Import('env')

cxxenv = env.Clone()

# build object files in hidden sub directory
cxxenv['OBJPREFIX'] = '.obj/'

#env.SharedLibrary('bashes',[
#	'H5File.cc','DataStamps.cc','PriorStamps.cc','H5Save.cc','Prior.cc','ImageFile.cc','ThreadPool.cc'
#	],LIBS=['galsim','cfitsio','hdf5','boost_thread','boost_system'])

cxxenv.SharedLibrary('#lib/bashes',[
	'Estimator.cc'
	],LIBS=['boost_thread','boost_system'])
